apiVersion: v1
kind: Pod
metadata:
  name: sufficient-resources-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    resources:
      requests:
        cpu: "1"  # בקשה למעבד אחד כולו
        memory: "500Mi"  # בקשה ל-500 מגה-בייט זיכרון